<?php
session_start();
require_once 'config.php';


if (!isset($_SESSION['user_id'])) { die("You must be logged in."); }


if (!isset($_GET['resultID'])) { die("Report not found."); }

$resultID = $_GET['resultID'];
$studentID = $_SESSION['user_id'];

$sql = "SELECT r.*, e.subject, e.exam_date, u.name as StudentName 
        FROM results r 
        JOIN exams e ON r.examID = e.examID 
        JOIN users u ON r.studentID = u.id
        WHERE r.resultID = ? AND r.studentID = ?"; 

$stmt = $pdo->prepare($sql);
$stmt->execute([$resultID, $studentID]);
$report = $stmt->fetch();

if (!$report) { die("Report not found or access denied."); }


$filename = "Exam_Result_" . str_replace(' ', '_', $report['subject']) . ".doc";

header("Content-Type: application/vnd.ms-word");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("content-disposition: attachment;filename=$filename");


<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
        .score-box { background-color: #f0f0f0; border: 1px solid #ccc; padding: 20px; text-align: center; margin: 20px 0; }
        h1 { color: #2c3e50; }
    </style>
</head>
<body>
    <div class="header">
        <h1>EXAM RESULT REPORT</h1>
        <h3>Automated Assessment System</h3>
    </div>

    <p><strong>Student Name:</strong> <?php echo $report['StudentName']; ?></p>
    <p><strong>Subject:</strong> <?php echo $report['subject']; ?></p>
    <p><strong>Date:</strong> <?php echo date("d.m.Y H:i", strtotime($report['exam_date'])); ?></p>
    
    <div class="score-box">
        <h2>SCORE OBTAINED</h2>
        <h1 style="font-size: 40px; color: #e74c3c;"><?php echo $report['score']; ?></h1>
    </div>

    <h3>System Feedback:</h3>
    <div style="border: 1px solid #ddd; padding: 15px; background-color: #fff;">
        <?php echo nl2br($report['feedback'] ? $report['feedback'] : "No feedback provided yet."); ?>
    </div>

    <br><br>
    <p style="text-align: center; font-size: 12px; color: #888;">
        This document was automatically generated by the system.<br>
        <?php echo date("d.m.Y H:i"); ?>
    </p>
</body>
</html>
